name: ðŸ”„ CI - Rebase
on:
  workflow_run:
    workflows: ["ðŸ§ª CI - Check"]
    types:
      - completed
jobs:
  merge:
    if: >
      github.event.workflow_run.head_branch == 'main' &&
      github.event.workflow_run.conclusion == 'success'
    name: ðŸ”„ Rebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Rebase main to release
        uses: cyberskill-world/.github/actions/rebase-branch@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          FROM: main
          TO: release
