name: ðŸ”„ CI - Sync
on:
  workflow_run:
    workflows: ["ðŸ§ª CI - Check"]
    types:
      - completed
jobs:
  sync:
    if: >
      github.event.workflow_run.head_branch == 'main' &&
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“¥ Checkout repository
        uses: actions/checkout@v4
      - name: ðŸ”„ Merge main into release
        uses: cyberskill-world/.github/actions/merge-branch@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          FROM: main
          TO: release
