name: ðŸŒ CI - Distribute
on:
  workflow_run:
    workflows: ["ðŸš€ CI - Deploy"]
    types:
      - completed
jobs:
  distribute:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    uses: cyberskill-world/.github/.github/workflows/distribute.yml@main
    secrets: inherit
